zopefoundation/RestrictedPython

- pytest.ini
- src/RestrictedPython/test_helper.py
- src/RestrictedPython/tests/security_in_syntax.py
- src/RestrictedPython/transformer.py
- tests/fixtures/class.py
- tests/fixtures/lambda.py
- tests/fixtures/restricted_module.py
- tests/fixtures/restricted_module_py3.py
- tests/fixtures/security_in_syntax.py
- tests/fixtures/unpack.py
- tests/fixtures/unpack_py3.py
- tests/test_print.py
- tests/test_restrictions.py
@loechel still WIP ... Check the changes done. I hope this helps.
> Python3 update

- tox.ini
There is now a released version of pytest-mock which supports Python 3.6.
> Use released pytest-mock

- src/RestrictedPython/transformer.py
- tests/test_print_function.py
- tests/test_transformer.py
Reason: ast nodes which have a `visit_` function had also to be in the
whitelist. This was an unnecessary duplication.
The most important part of art the methods `generic_visit` and
`node_contents_visit`.
Additionally I forbid all ast nodes which are not yet covered by tests.
> Get rid of the whitelist.

- src/RestrictedPython/transformer.py
- tests/__init__.py
- tests/test_transformer.py
plus refactor the tests into parts.
Adresses a comment of @stephan-hof in #16.
> Fix comments for try-except

- src/RestrictedPython/tests/security_in_syntax.py
- src/RestrictedPython/transformer.py
- tests/test_transformer.py
Remove an old tests which was already covered by the new tests.
> Transform tests.

- CHANGES.txt
- src/RestrictedPython/RCompile.py
- src/RestrictedPython/__init__.py
- src/RestrictedPython/compile.py
- tests/test_compile.py
- tests/test_transformer.py
This requires to change the old implementation, too.
> compile_restricted* now returns a namedtuple to ease usage.

- tests/__init__.py
- tests/test_compile.py
- tests/test_print_stmt.py
- tests/test_transformer.py
Use more sane names.
Adapt tests to use the new marks more widely.
> Clean up pytest marks

- src/RestrictedPython/Guards.py
- src/RestrictedPython/tests/restricted_module.py
- src/RestrictedPython/tests/testRestrictions.py
Adding built-in function 'set' to `safe_builtins`. Sets can be created with the {x, y} notation, but there's no way to create an empty set.
> Add built-in function 'set'

- src/RestrictedPython/Guards.py
- src/RestrictedPython/tests/restricted_module.py
- src/RestrictedPython/tests/testRestrictions.py
Reverts zopefoundation/RestrictedPython#11
The tests weren't actually being run on Travis, and the new test [fails](https://travis-ci.org/zopefoundation/RestrictedPython/builds/207043175).
/cc @ehfeng
> Revert "Add built-in function 'set'"

- .travis.yml
```bash
$ /opt/Python-2.7.13/bin/virtualenv /tmp/RP
New python executable in /tmp/RP/bin/python
Installing setuptools, pip, wheel...done.
$ /tmp/RP/bin/pip install -U setuptools pip
Requirement already up-to-date: setuptools in /tmp/RP/lib/python2.7/site-packages
Requirement already up-to-date: pip in /tmp/RP/lib/python2.7/site-packages
Requirement already up-to-date: packaging>=16.8 in /tmp/RP/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: appdirs>=1.4.0 in /tmp/RP/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: six>=1.6.0 in /tmp/RP/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: pyparsing in /tmp/RP/lib/python2.7/site-packages (from packaging>=16.8->setuptools)
$ /tmp/RP/bin/pip install . …
```
> Use buildout on Travis.

- src/RestrictedPython/Eval.py
- src/RestrictedPython/tests/testRestrictions.py
- src/RestrictedPython/transformer.py
- tests/test_compile.py
- tests/test_eval.py
- tests/transformer/test_transformer.py
This ports `Eval.py` to python3 by using the methods from `compile.py`.
As a side effect I brought back support for `used_names` in  `RestrictingNodeTransformer`.
I know nowadays `used_names` could have been a `set()`, but I didn't dare to change the API.
Since `used_names` is used by other code outside of RestrictedPython.
> Port eval py

- src/RestrictedPython/Utilities.py
- tests/builtins/test_utilities.py
This is for backwards compatibility with existing code which might use sets.
> Allow `sets` again.

- src/RestrictedPython/Guards.py
There's a backport this package part of `future` which provides other
builtins (and breaks tests if it's installed).
> Do not attempt to import builtins on Python 2.7

- src/RestrictedPython/Guards.py
- tests/test_Guards.py
This is only needed for Python 3.
We detected it while porting AccessControl which defines a `class` in its tests.
> Allow to create new classes with `safe_builtins` activated.

- docs/usage/basic_usage.rst
- src/RestrictedPython/transformer.py
- tests/__init__.py
- tests/test_Guards.py
- tests/test_print_function.py
- tests/transformer/test_transformer.py
AccessControl needs to have a default metaclass in order to guard_writes etc.
This PR implements this feature for Python 3 and supports decorators and base classes.
It is still not allowed to specify metaclasses in restricted python code.
> Enable default metaclass.

- src/RestrictedPython/Eval.py
Name expression can only be "Load", so that the if makes no sense.
> Change checking for type of expression context to an assert. 

- tests/test_eval.py
Increase code coverage to nearly 100%.
> Increase code coverage for Eval module.

- docs/CHANGES.rst
- src/RestrictedPython/Guards.py
- src/RestrictedPython/README.rst
- src/RestrictedPython/_compat.py
- tests/test_Guards.py
It prevents from using the ``format()`` method on str/unicode as it is not
safe, see: http://lucumr.pocoo.org/2016/12/29/careful-with-str-format/
This fix supersedes #80.
> Security issue: Ship with a default implementation for _getattr_

- README.rst
- docs/CHANGES.rst
- docs/index.rst
- src/RestrictedPython/_compat.py
- src/RestrictedPython/compile.py
- tests/test_compile.py
PyPy cannot be restricted enough by RestrictedPython.
Other implementation might have other or similar issues.
> Warn when using another Python implementation than CPython.

- docs/CHANGES.rst
- src/RestrictedPython/Eval.py
- tests/test_eval.py
> Allow list comprehensions in ``RestrictionCapableEval.eval()``.

- README.rst
- docs/CHANGES.rst
- docs/RestrictedPython3/index.rst
- docs/api/index.rst
- docs/basics/index.rst
- docs/contributing/index.rst
- docs/idea.rst
- docs/install/index.rst
- docs/roadmap/index.rst
- docs/upgrade/index.rst
- docs/usage/api.rst
- docs/usage/basic_usage.rst
- docs/usage/framework_usage.rst
- docs/usage/policy.rst
- setup.py
- src/RestrictedPython/README.rst
* Close open file descriptors in setup.py
* Some cleanup in restructured text files
> Housekeeping

- docs/CHANGES.rst
- setup.cfg
- src/RestrictedPython/transformer.py
- tests/transformer/test_call.py
- tests/transformer/test_classdef.py
- tests/transformer/test_functiondef.py
fix #104
It allow a subset of the python datamodel names that are implicit used in special cases.
> Allow a set of datatype methods like __init__ for class methods

- docs/CHANGES.rst
- src/RestrictedPython/compile.py
- tests/test_compile_restricted_function.py
It now also returns a `CompileResult` instead of raising a `SyntaxError`.
Fixes zopefoundation/Products.PythonScripts#11
> Fix compile_restricted_function() called with SyntaxError in function body.

- tests/transformer/test_comparators.py
this partially solves issue #113
> separate List, Set and Dict check for In and NotIn

- src/RestrictedPython/transformer.py
- tests/test_Guards.py
- tests/test_imports.py
builtins is a dangerous element in RestrictedPython, as it contains the whole Programming Environment with all modules and control access to them.
Should be forbidden to access.
Fixes #115
> Several checks for __builtins__ and builtins.

- src/RestrictedPython/compile.py
- tests/test_compile.py
> fix error if a SyntaxError is raised, but no text is provided

- src/RestrictedPython/Utilities.py
- tests/builtins/test_utilities.py
change behaviour of same_type function in RestrictedPython.Utilities so that it returns a bool instaed of 0 or 1.
Fixes #122
> change behaviour of same_type function

- appveyor.yml
- setup.py
- tox.ini
* make the isort explicite check result ignored, as that is also in the flake8 check via flake8-isort, so we always got the full problem list. 
* fix one linting issue in setup.py
> lint config

- appveyor.yml
https://www.appveyor.com/docs/windows-images-software/#python does not
list Python 3.8 as an available version.
(In fact Python 3.8 is not out yet.)
Having it listed in appveyor.yml confuses tools like my
check-python-versions, as they detect an inconsistency between supported
Python versions listed in appveyor.yml with those listed eg. in
setup.py.
> There's no Python 3.8 on Appveyor

- src/RestrictedPython/transformer.py
- tests/test_compile.py
- tests/test_print_stmt.py
> Fix typos.

- docs/usage/basic_usage.rst
When using for loops, we faced the error `_getiter_` not defined. This is the workaround for resolving it.
> Added statement to resolve getiter error

- docs/CHANGES.rst
- src/RestrictedPython/transformer.py
- tests/transformer/test_fstring.py
This fixes #123.
Note that f-strings are very different from using `str.format` since they're actually compiled to bytecode and thus the restricted exec transformer is able to work its magic on the expression contained.
> Add support for f-strings

- .travis.yml
- appveyor.yml
- setup.cfg
- tox.ini
On CI (Travis and Appveyor) the lint Checks does not run and therefore the master is dirty.
This Pull-Request is a base to fix the dirty Master and ensure that the Linting ( Convention Checks ) are run on each push to github. This fixes #172  
By the way therefor this Pull Request should be red on CI to show that the errors now show up.
As a second step then a fix to the dirty master is necessary to fix the lining errors.
> Fix problems on CI, conventions are not checked.

- docs/CHANGES.rst
- src/RestrictedPython/transformer.py
- tests/transformer/test_base_types.py
Ellipsis is not necessary to allow for the changes in Python 3.8, where Constant replaces Num, Str, Bytes, NameConstant and Ellipsis.
https://docs.python.org/dev/whatsnew/3.8.html\#deprecated
https://bugs.python.org/issue36917\#msg342583 shows a better solution to check for Ellipsis, so we could go back to old and more secure behaviour.
So it partial reverts #150
> Partial Revert of Merge/Pull-Request #150 - Disallow Ellipsis again.

- docs/contributing/ast/python2_6.ast
- docs/contributing/ast/python2_7.ast
- docs/contributing/ast/python3_0.ast
- docs/contributing/ast/python3_1.ast
- docs/contributing/ast/python3_2.ast
- docs/contributing/ast/python3_3.ast
- docs/contributing/ast/python3_4.ast
- docs/contributing/ast/python3_5.ast
- docs/contributing/ast/python3_6.ast
- docs/contributing/ast/python3_7.ast
- docs/contributing/ast/python3_8.ast
- docs/contributing/changes_from26to27.rst
- docs/contributing/changes_from30to31.rst
- docs/contributing/changes_from31to32.rst
- docs/contributing/changes_from32to33.rst
- docs/contributing/changes_from33to34.rst
- docs/contributing/changes_from34to35.rst
- docs/contributing/changes_from35to36.rst
- docs/contributing/changes_from36to37.rst
- docs/contributing/changes_from37to38.rst
- docs/contributing/index.rst
Some of the documentation got removed, when cutting the 4.0 release.
I readd some of the documentation as a remainder how RestrictedPython works internally and the AST Grammar files as they help to understand changes between Python Versions that may affects RestrictedPython.
> readd some of the documentation that helps to understand how RestrictedPython works internally

- tox.ini
This should fix the AppVeyor tests.
TravisCI does not seem to show these problem because it caches the old version.
> Require Python 2 compatible pytest-html version.

- docs/CHANGES.rst
- src/RestrictedPython/compile.py
- tests/test_compile_restricted_function.py
Fixes #181 - fashioned after #137
> Fix ``compile_restricted_function`` with SyntaxErrors that have no text

- .meta.toml
- CHANGES.rst
- constraints.txt
- src/RestrictedPython/transformer.py
- tox.ini
> Avoid deprecation warnings when using Python 3.8+.

- CHANGES.rst
- src/RestrictedPython/transformer.py
As the PR is already merged here a PR to improve it a bit further.
> Improve the inspect PR.

- CHANGES.rst
- src/RestrictedPython/transformer.py
Supercedes #257 and concentrates on the DeprecationWarnings only.
> Fix DeprecationWarnings under Python 3.12

- CHANGES.rst
- src/RestrictedPython/transformer.py
- tests/transformer/operators/test_arithmetic_operators.py
> Add support for the matmul (`@`) operator.

- CHANGES.rst
- docs/usage/basic_usage.rst
- src/RestrictedPython/transformer.py
- tests/test_compile.py
> enable single mode

- CHANGES.rst
- src/RestrictedPython/Guards.py
- tests/test_Guards.py
fix a possible breakout possibility in the provided safer_getattr methode in Guards
> safer_getattr

- CHANGES.rst
- src/RestrictedPython/Guards.py
- tests/test_Guards.py
add an additional check for potential breakout capability via Inspection Attributes Names in the provided safer_getattr method.
> additional check for safer_getattr 

- CHANGES.rst
- src/RestrictedPython/Guards.py
- tests/test_Guards.py
Fixed #287.
`safer_getattr_raise` is similar to `safer_getattr` but handles its parameter `default` like `getattr`. In particular, it raises `AttributeError` if the attribute lookup fails and no `default` has been provided.
> new function `safer_getattr_raise`

- .github/workflows/tests.yml
- .meta.toml
- .pre-commit-config.yaml
- CHANGES.rst
- pyproject.toml
- setup.py
- tox.ini
- **Configuring for pure-python**
- **Allow Python 3.14.**
- **Add change log entry.**
- **Configuring for pure-python**
See also #298
> Preliminary Python 3.14 support.

- .github/workflows/pre-commit.yml
- .github/workflows/tests.yml
- .meta.toml
- .pre-commit-config.yaml
- pyproject.toml
- tox.ini
Fixes a template typo and updates some tool versions
> - update to latest zope.meta templates
