zopefoundation/RestrictedPython

.travis.yml
And update to test the supported versions.
Caution: This is a PR for the Python 3 branch.
=> Use tox for the tests on Travis.

.travis.yml
I'd like to get information about coverage evolvement.
=> Try to use coveralls

src/RestrictedPython/Guards.py, src/RestrictedPython/Utilities.py, src/RestrictedPython/tests/testRestrictions.py
* remove commented out parts
* remove no longer used method
=> Clean up code

.coveragerc, .gitignore, docs/CHANGES.rst, setup.cfg, src/RestrictedPython/SelectCompiler.py, tox.ini
Those configs are edited to be better readable, to store output into a reports directory
=> better configuration for tests

tests/transformer/test_assert.py, tests/transformer/test_comparators.py, tests/transformer/test_conditional.py, tests/transformer/test_generic.py, tests/transformer/test_import.py, tests/transformer/test_loop.py
travis build was broken, this just fix the isort test
=> fix isort orders which are broken

.travis.yml, tox.ini
Not every developer (e. g. me) has the more general ones.
=> Use actual python versions for the linting.

appveyor.yml
=> Change appveyor settings

docs/CHANGES.rst, src/RestrictedPython/transformer.py, tests/transformer/test_import.py
=> deny * imports

tests/test_iterating_over_dict_items.py
Add a Test for the described pattern in #129 
It did not solve that, but describes how that could be solved in the RestrictedPython way.
Additional Documentation is necessary.
=> Add Tests for iterating over dict items

src/RestrictedPython/Limits.py, tests/builtins/test_limits.py
This is a proposal for solving #121
=> Modify Error given on range limit

.travis.yml, appveyor.yml, setup.py, src/RestrictedPython/_compat.py, src/RestrictedPython/transformer.py, tests/transformer/test_breakpoint.py
Python3.7 new Features: https://docs.python.org/3/whatsnew/3.7.html
The only thing I see is ```breakpoint()``` builtin function. 
solves #98
=> Make RestrictedPython compatible to Python3.7.

.gitignore, README.rst, docs/CHANGES.rst, docs/RestrictedPython4/index.rst, docs/idea.rst, docs/index.rst, docs/old_README.rst, docs/upgrade/index.rst, docs/upgrade_dependencies/index.rst, docs/usage/api.rst, docs/usage/basic_usage.rst, docs/usage/policy.rst, src/RestrictedPython/Guards.py, src/RestrictedPython/__init__.py, tests/test_Guards.py, tests/test_compile_restricted_function.py, tests/test_iterating_over_dict_items.py
=> Safer getattr

.travis.yml, docs/CHANGES.rst, setup.py, src/RestrictedPython/_compat.py, src/RestrictedPython/transformer.py, tests/test_compile.py, tests/transformer/test_base_types.py, tox.ini
Closes #145 as it supersedes it.
=> Add preliminary Python 3.8 support.

docs/usage/policy.rst
Just stumbled over them when reading your docs :)
=> Fix typos.

tests/transformer/test_dict_comprehension.py
See https://github.com/python/cpython/commit/c8a35417db8853a253517a3e5190e174075c6384
=> Fix broken dictcomp test on Python 3.8

tests/transformer/test_dict_comprehension.py, tests/transformer/test_fstring.py
This resolves the Red Master after #173
=> fix Coding conventions after #173

setup.py
Project URLs to show in PyPI https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls
and necessary Python Version Check on Install : https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires From PEP 440 https://www.python.org/dev/peps/pep-0440/
=> Add more descriptive features into setup.py for pip and pypi.

docs/CHANGES.rst, setup.py
=> remove setuptools from install_requires

.travis.yml, appveyor.yml, constraints.txt, tox.ini
=> simplify tox, travis / appveyor setup

docs/CHANGES.rst, src/RestrictedPython/Guards.py, tests/test_Guards.py
=> Add support for the ``bytes`` and ``sorted`` builtins

CHANGES.rst, setup.py
=> Add support for Python 3.9.

CHANGES.rst
=> Add support for Python 3.10.
